[build]
builder = "DOCKERFILE"
dockerfilePath = "server/Dockerfile"

[deploy]
startCommand = "bun run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

